//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchSocket.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TouchSocketDmtpResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TouchSocketDmtpResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouchSocket.Dmtp.Resources.TouchSocketDmtpResource", typeof(TouchSocketDmtpResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The channel with ID {0} already exists. 的本地化字符串。
        /// </summary>
        public static string ChannelExisted {
            get {
                return ResourceManager.GetString("ChannelExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create write stream from &apos;{0}&apos;, information: {1}. 的本地化字符串。
        /// </summary>
        public static string CreateWriteStreamFail {
            get {
                return ResourceManager.GetString("CreateWriteStreamFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        public static string DirectoryExisted {
            get {
                return ResourceManager.GetString("DirectoryExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory &apos;{0}&apos; does not exist. 的本地化字符串。
        /// </summary>
        public static string DirectoryNotExists {
            get {
                return ResourceManager.GetString("DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DmtpFileTransferActor is empty, it may be necessary to enable the DmtpFileTransfer plugin. 的本地化字符串。
        /// </summary>
        public static string DmtpFileTransferActorNull {
            get {
                return ResourceManager.GetString("DmtpFileTransferActorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DmtpRpcActor is empty, it may be necessary to enable the DmtpRpc plugin. 的本地化字符串。
        /// </summary>
        public static string DmtpRpcActorArgumentNull {
            get {
                return ResourceManager.GetString("DmtpRpcActorArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        public static string FileExisted {
            get {
                return ResourceManager.GetString("FileExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file length is too long. 的本地化字符串。
        /// </summary>
        public static string FileLengthTooLong {
            get {
                return ResourceManager.GetString("FileLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file &apos;{0}&apos; does not exist. 的本地化字符串。
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event operator exception. 的本地化字符串。
        /// </summary>
        public static string GetEventArgsFail {
            get {
                return ResourceManager.GetString("GetEventArgsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are still {0} resources that have not been completed. 的本地化字符串。
        /// </summary>
        public static string HasUnFinished {
            get {
                return ResourceManager.GetString("HasUnFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error reading file length. 的本地化字符串。
        /// </summary>
        public static string LengthErrorWhenRead {
            get {
                return ResourceManager.GetString("LengthErrorWhenRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RedisActor is empty, it may be necessary to enable the RedisActor plugin. 的本地化字符串。
        /// </summary>
        public static string RedisActorNull {
            get {
                return ResourceManager.GetString("RedisActorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The RemoteAccessActor is empty, and the RemoteAccess plugin may need to be enabled. 的本地化字符串。
        /// </summary>
        public static string RemoteAccessActorNull {
            get {
                return ResourceManager.GetString("RemoteAccessActorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The remote terminal refused the operation and provided feedback message: {0}. 的本地化字符串。
        /// </summary>
        public static string RemoteRefuse {
            get {
                return ResourceManager.GetString("RemoteRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The RemoteStreamActor is empty, and the RemoteStream plugin may need to be enabled. 的本地化字符串。
        /// </summary>
        public static string RemoteStreamActorNull {
            get {
                return ResourceManager.GetString("RemoteStreamActorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The resource corresponding to resource handle {0} could not be found, possibly the operation has timed out. 的本地化字符串。
        /// </summary>
        public static string ResourceHandleNotFind {
            get {
                return ResourceManager.GetString("ResourceHandleNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routing of this packet is not allowed, information: {0}. 的本地化字符串。
        /// </summary>
        public static string RoutingNotAllowed {
            get {
                return ResourceManager.GetString("RoutingNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function execution exception, details: {0}. 的本地化字符串。
        /// </summary>
        public static string RpcInvokeException {
            get {
                return ResourceManager.GetString("RpcInvokeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method has been disabled. 的本地化字符串。
        /// </summary>
        public static string RpcMethodDisable {
            get {
                return ResourceManager.GetString("RpcMethodDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The public method was not found, or the method is not marked as Rpc. 的本地化字符串。
        /// </summary>
        public static string RpcMethodNotFind {
            get {
                return ResourceManager.GetString("RpcMethodNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel setting failed. 的本地化字符串。
        /// </summary>
        public static string SetChannelFail {
            get {
                return ResourceManager.GetString("SetChannelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The flow container is empty. 的本地化字符串。
        /// </summary>
        public static string StreamBucketNull {
            get {
                return ResourceManager.GetString("StreamBucketNull", resourceCulture);
            }
        }
    }
}
