blank_issues_enabled: false

contact_links:
  - name: 使用文档
    url: https://touchsocket.net//
    about: 一款简单易用的基础网络通讯组件库。
  - name: 慷慨赞助
    url: https://touchsocket.net//docs/current/donate
    about: 慷慨赞助
