//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchSocket.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TouchSocketCoreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TouchSocketCoreResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouchSocket.Core.Resources.TouchSocketCoreResource", typeof(TouchSocketCoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 This adapter is already in use by another terminal, please create a new object. 的本地化字符串。
        /// </summary>
        public static string AdapterAlreadyUsed {
            get {
                return ResourceManager.GetString("AdapterAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; is empty. 的本地化字符串。
        /// </summary>
        public static string ArgumentIsNull {
            get {
                return ResourceManager.GetString("ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current byteBlock does not allow reading. 的本地化字符串。
        /// </summary>
        public static string BlockReaderNotAllowReading {
            get {
                return ResourceManager.GetString("BlockReaderNotAllowReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The config is empty. 的本地化字符串。
        /// </summary>
        public static string ConfigIsNull {
            get {
                return ResourceManager.GetString("ConfigIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default situation. 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred with the message &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file &apos;{0}&apos; does not exist. 的本地化字符串。
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file at path &apos;{0}&apos; has been loaded in write only mode. 的本地化字符串。
        /// </summary>
        public static string FileOnlyWrittenTo {
            get {
                return ResourceManager.GetString("FileOnlyWrittenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file at path &apos;{0}&apos; has been loaded in read only mode. 的本地化字符串。
        /// </summary>
        public static string FileReadOnly {
            get {
                return ResourceManager.GetString("FileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For enumeration type: &apos;{0}&apos;, an invalid enumeration value &apos;{1}&apos; was set. 的本地化字符串。
        /// </summary>
        public static string InvalidEnum {
            get {
                return ResourceManager.GetString("InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of parameter &apos;{0}&apos; is an invalid parameter. 的本地化字符串。
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer backed by array was expected. 的本地化字符串。
        /// </summary>
        public static string MemoryGetArrayFail {
            get {
                return ResourceManager.GetString("MemoryGetArrayFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The token message with &apos;{0}&apos; is not registered. 的本地化字符串。
        /// </summary>
        public static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No public constructor found for type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string NotFindPublicConstructor {
            get {
                return ResourceManager.GetString("NotFindPublicConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object instance with type &apos;{0}&apos; and HashCode &apos;{1}&apos; has been released. 的本地化字符串。
        /// </summary>
        public static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation has been canceled. 的本地化字符串。
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation timed out. 的本地化字符串。
        /// </summary>
        public static string OperationOvertime {
            get {
                return ResourceManager.GetString("OperationOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation successful. 的本地化字符串。
        /// </summary>
        public static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin &apos;{0}&apos; is null, it may be missing registration information in the container. 的本地化字符串。
        /// </summary>
        public static string PluginIsNull {
            get {
                return ResourceManager.GetString("PluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type: {0}, Information: {1} 的本地化字符串。
        /// </summary>
        public static string ResultToString {
            get {
                return ResourceManager.GetString("ResultToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No stream file corresponding to path &apos;{0}&apos; was found. 的本地化字符串。
        /// </summary>
        public static string StreamNotFind {
            get {
                return ResourceManager.GetString("StreamNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream file corresponding to path &apos;{0}&apos; is still being applied by the &apos;{1}&apos; object. 的本地化字符串。
        /// </summary>
        public static string StreamReferencing {
            get {
                return ResourceManager.GetString("StreamReferencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to convert string &apos;{0}&apos; to type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string StringParseToTypeFail {
            get {
                return ResourceManager.GetString("StringParseToTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The token message with &apos;{0}&apos; has been registered. 的本地化字符串。
        /// </summary>
        public static string TokenExisted {
            get {
                return ResourceManager.GetString("TokenExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown error. 的本地化字符串。
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create an instance of unregistered type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string UnregisteredType {
            get {
                return ResourceManager.GetString("UnregisteredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of parameter &apos;{0}&apos; is&apos; {1} &apos;, which is outside the range of&apos; {2} &apos;to&apos; {3} &apos;. 的本地化字符串。
        /// </summary>
        public static string ValueBetweenAnd {
            get {
                return ResourceManager.GetString("ValueBetweenAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of parameter &apos;{0}&apos; is&apos; {1} &apos;, which is less than&apos; {2} &apos;. 的本地化字符串。
        /// </summary>
        public static string ValueLessThan {
            get {
                return ResourceManager.GetString("ValueLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of parameter &apos;{0}&apos; is&apos; {1} &apos;, which is greater than&apos; {2} &apos;. 的本地化字符串。
        /// </summary>
        public static string ValueMoreThan {
            get {
                return ResourceManager.GetString("ValueMoreThan", resourceCulture);
            }
        }
    }
}
